name: Telegram Ingestion

on:
  repository_dispatch:
    types: [telegram_message]

permissions:
  contents: write

concurrency:
  group: learning-bot-ingestion
  cancel-in-progress: false

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        -uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: requirements-ingest.txt

      - name: Install dependencies
        run: pip install -r requirements-ingest.txt

      - name: Show payload
        run: echo '${{ toJson(github.event.client_payload) }}'

      - name: Export payload
        run: |
          echo "MSG_TEXT=${{ github.event.client_payload.text }}" >> $GITHUB_ENV
          echo "MSG_USER=${{ github.event.client_payload.user }}" >> $GITHUB_ENV
          echo "MSG_TIME=${{ github.event.client_payload.timestamp }}" >> $GITHUB_ENV

      - name: Run tracker
        run: python scripts/tracker.py

      - name: Run NLP parser
        run: python scripts/nlp_parser.py

      - name: Commit updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # save local changes
          git stash

          # pull latest repo state
          git pull --rebase

          # restore local changes
          git stash pop || true

          git add logs/learning-log.md data/events.csv

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "update learning dataset"
            git push
          fi